### ISSUE TITLE
[TODO] Various things

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/WearableBackpacks#12]
- [ ] Fully fix rendering
- [ ] Fully fix chest-based slots
- [ ] Add rudimentary trinkets compat
- [ ] Maybe come up with some enchantments exclusive to backpacks, that can be applied regardless of config settings?

**Comment by Sunconure11** [comment]
Enchantment ideas:

- [ ] Deepest Pockets: Expands slots even more. Has 2 levels. This slows the player down somewhat, though.
- [ ] Toughened Leather: Your backpack is toughened, and can serve as armor, regardless of config settings. Has 2 levels. Dungeon only.
- [ ] Maw of the Void: Your backpack may eat random items. Curse!
- [ ] Endless Abyss: You may find random items from vanilla, and if specified in the config, other mods, in your backpack, from time to time. This only works if there are free slots to use.
- [ ] Refill: Refills specific items so as long as they are in your backpack, by taking them from your inventory.
- [ ] Pickup: Automatically picks up items from farther away, and stores them in your backpack. Has 3 levels.
- [ ] Litterbug: Items will drop out of your backpack into the world, at random intervals. Curse!

Enchantment integration from other mods:

- [ ] Soulbound-type enchants from other mods work on this

Other stuff:

- [ ] Naming a backpack "jeb_" makes it cycle through the rainbow
